sonar.projectKey=71405245_FIN_DE_CURSO

sonar.sources=SIMA/frontend,SIMA/backend

sonar.exclusions=**/node_modules/**,**/docs/**,**/sima_db_backup/**,**/coverage/**,**/*.json

sonar.sourceEncoding=UTF-8

sonar.organization=71405245

sonar.javascript.lcov.reportPaths=SIMA/backend/coverage/lcov.info

sonar.branch.name=mejoras