# Generated by Django 4.2.18 on 2026-03-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_seccion'),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='curso',
        ),
        migrations.AddField(
            model_name='matricula',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academico.seccion'),
            preserve_default=False,
        ),
    ]
