# Generated by Django 4.2.18 on 2026-04-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='aula',
        ),
        migrations.AddField(
            model_name='seccion',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.salon'),
        ),
    ]
