# Generated by Django 4.2.18 on 2026-05-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='limite_creditos',
            field=models.IntegerField(default=24),
        ),
    ]
