name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - mejoras
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      # Descargar repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ← Recomendado agregar esto para Sonar

      # Instalar dependencias backend
      - name: Install backend dependencies
        run: |
          cd SIMA/backend
          npm install

      # Ejecutar tests con Jest y generar coverage
      - name: Run Jest tests
        run: |
          cd SIMA/backend
          npm test

      # Ejecutar análisis SonarCloud
      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io