# Generated by Django 4.2.18 on 2026-05-03 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matricula', '0002_remove_matricula_curso_matricula_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_preferido', models.CharField(choices=[('cualquiera', 'Cualquier Turno'), ('mañana', 'Mañana (07:00 - 13:00)'), ('tarde', 'Tarde (14:00 - 18:00)'), ('noche', 'Noche (18:00 - 22:00)')], default='cualquiera', max_length=20)),
                ('dias_maximos', models.IntegerField(default=5, help_text='Cantidad máxima de días que deseas asistir a la universidad.')),
                ('cantidad_cursos', models.IntegerField(default=5, help_text='Cantidad de cursos que deseas llevar este ciclo.')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_horario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
